kind: pipeline
type: docker
name: docker-compose-example

environment:
  GIT_TAG: $(git rev-parse --short HEAD)
  PROJECT: 'live4-data-center-service'
  IMAGE_NAME: 'live4-data-center-drone'

steps:
  - name: Set GIT_TAG
    image: plugins/git
    settings:
      credentials:
        from_secret: devops-ssh  # 替换为您保存 GitHub 凭据的 Drone CI Secret 的名称
    commands:
      - export GIT_TAG=$(git rev-parse --short HEAD)
      - echo $GIT_TAG

  - name: Print Environment Variables
    image: alpine
    commands:
      - echo $GIT_TAG

# environment:
#   GIT_TAG: ''
#   PROJECT: 'live4-data-center-service'
#   IMAGE_NAME: 'live4-data-center-drone'

# steps:

#   - name: checkout
#     image: alpine/git
#     commands:
#       - echo hello $GIT_TAG bye
#       - git clone --recursive https://github.com/bobiMedia/live4-data-center-service.git .
#       - export GIT_TAG=$(git rev-parse --short HEAD)  # 获取 Git 提交的前7个字符作为 TAG
#       - echo "GIT_TAG=${GIT_TAG}" >> $DRONE_ENV_FILE 
#       - echo "GIT_TAG=${GIT_TAG}" > git_tag.txt
#     when:
#       event:
#         exclude:
#           - push

#   - name: generate-random-tag
#     image: bash
#     commands:
#       - echo hello $DRONE_ENV_FILE bye
#       - source git_tag.txt
#       - echo Generated random tag $GIT_TAG