kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.20.6
    commands:
      - go build
    when:
      event:
        - push
        - pull_request
      include:
        - main.go
  - name: integration-test
    image: golang:1.20.6
    commands:
      - docker run -d --name postgres -e POSTGRES_DB=dev_test -e POSTGRES_USER=testRoot -e POSTGRES_PASSWORD=testRoot postgres:11
      - docker run -d --name redis -p 6379:6379 redis:7.2.0
      - docker run --link postgres:postgre --link redis:redis --name my-golang-container -v $(pwd):/go/src/app -w /go/src/app golang:1.20.6 go test ./integration/... -ci=1 -v count=1

