kind: pipeline
type: docker

name: default

steps:
  - name: wait-for-postgres
    image: postgres:latest  # 使用一個 Postgres 的 Docker 映像
    commands:
      - sh
      - -c
      - |
        until pg_isready -h $${POSTGRES_HOST} -p $${POSTGRES_PORT}; do
          echo "Waiting for PostgreSQL to start..."
          sleep 1
        done

  - name: wait-for-redis
    image: redis:latest  # 使用一個 Redis 的 Docker 映像
    commands:
      - sh
      - -c
      - |
        until redis-cli -h $${REDIS_HOST} -p $${REDIS_PORT} ping; do
          echo "Waiting for Redis to start..."
          sleep 1
        done

  - name: run-tests
    image: golang:1.20.6
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: dev_test
      POSTGRES_USER: testRoot
      POSTGRES_PASSWORD: testRoot
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    commands:
      - go test ./integration/... -ci=1 -v count=1
