---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.16
    commands:
      - go build
    when:
      event:
        - push
        - pull_request
      include:
        - main.go
