kind: pipeline
name: default

steps:
  - name: start-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: dev_test
      POSTGRES_USER: testRoot
      POSTGRES_PASSWORD: testRoot
    commands:
      - dockerize -wait tcp://localhost:5432 -timeout 1m
    detach: true

  - name: start-redis
    image: redis:latest
    commands:
      - dockerize -wait tcp://localhost:6379 -timeout 1m
    detach: true

  - name: run-tests
    image: golang:1.20.6
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: dev_test
      POSTGRES_USER: testRoot
      POSTGRES_PASSWORD: testRoot
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    commands:
      - go test ./integration/... -ci=1 -v count=1
