kind: pipeline
type: docker
name: docker-compose-example


environment:
  GIT_TAG: ''
  PROJECT: 'live4-data-center-service'
  IMAGE_NAME: 'live4-data-center-drone'

steps:
  - name: checkout
    image: alpine/git
    commands:
      - echo hello $GIT_TAG bye
      - git clone --recursive https://github.com/bobiMedia/live4-data-center-service.git .
      - export GIT_TAG=$(git rev-parse --short HEAD)  # 获取 Git 提交的前7个字符作为 TAG
      - echo "GIT_TAG=${GIT_TAG}" >> $DRONE_ENV_FILE 
    when:
      event:
        exclude:
          - push

  - name: generate-random-tag
    image: bash
    commands:
      - echo hello $GIT_TAG bye
      - echo Generated random tag $GIT_TAG