kind: pipeline
type: docker
name: docker-compose-example


environment:
  GIT_TAG: ''
  PROJECT: 'live4-data-center-service'
  IMAGE_NAME: 'live4-data-center-drone'

steps:
  - name: generate-random-tag
    image: bash
    commands:
      - echo hello $GIT_TAG bye
      - GIT_TAG=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
      - echo Generated random tag $GIT_TAG