kind: pipeline
type: docker
name: docker-compose-example

steps:
  integration-tests:
    image: docker/compose:latest
    environment:
      DOCKER_HOST: tcp://docker-host:2375  # Replace with the actual Docker daemon address and port
    commands:
      - docker-compose up -d
      - sleep 10  # Wait for services to start, adjust as needed
      - npm install # or your application's build and test commands
      - npm test
      - docker-compose down
    when:
      event: [push, pull_request]
