kind: pipeline
type: docker
name: docker-compose-example

steps:
  - name: start
    image: docker/compose:latest
    commands:
      - docker-compose -version
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: run-tests
    image: golang:1.20.6
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: dev_test
      POSTGRES_USER: testRoot
      POSTGRES_PASSWORD: testRoot
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    commands:
      - go test ./integration/... -ci=1 -v count=1
 

  - name: stop
    image: docker/compose:latest
    commands:
      - docker-compose -f /drone/src/docker-compose.yml down
    volumes:
      - name: dockersock
        path: /var/run/docker.sock