version: '3.7'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=dev_test
      - POSTGRES_USER=testRoot
      - POSTGRES_PASSWORD=testRoot
    ports:
      - "5432:5432"
  redis:
    image: redis:7.2.0
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"